### ISSUE TITLE
Plugin documentation?

### ISSUE THREAD

**Issue by omerlh** [MindscapeHQ/fluent-plugin-raygun#1]
Where can I find documentation for this plugin?

**Comment by CmdrKeen** [comment]
Hi Omer,

We'll get some up shortly. We're not fluentd experts, so had made a possibly incorrect assumption that when you build plugins for fluentd it was a case of following the fluentd documentation for installing their plugins.

Will get one of the team to document the setup process.

Note also that this is a first cut, so appreciate any feedback on capturing more data.

**Comment by omerlh** [comment]
That for sure :) Thanks, looking forward to trying it out.

**Comment by mduncan26** [comment]
Hi @omerlh ,

We have just released our documentation for our fluentd plugin. It can be found here: https://raygun.com/docs/languages/fluentd. Thank you for your patience.

Regards,
Mitchell.

**Comment by omerlh** [comment]
I'll take a look, thanks!
